version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonardb
    ports:
      - "5432:5432"
  sonarqube:
    depends_on:
      - db
    restart: always
    image: sonarqube
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db/sonardb?currentSchema=public
    ports:
      - "9000:9000"
      - "443"